### ISSUE TITLE
Add geometry demo

### ISSUE THREAD

**Issue by Vtec234** [EdAyers/ProofWidgets4#7]
Add a demo using our [Penrose component](https://github.com/EdAyers/ProofWidgets4/blob/6fd1220b46c89d3ad437bdbcfda8babf3f360d98/ProofWidgets/Component/PenroseDiagram.lean) to visualize some goal states in synthetic Euclidean (or hyperbolic or ..) geometry. They [already have](https://github.com/penrose/penrose/tree/499cd21f39549abd317976f492b803a09ce2277d/packages/examples/src/geometry-domain) a good amount of Domain/Style programs for geometry. They look kind of like this:

![SIGGRAPH teaser - Euclidean Geometry](https://user-images.githubusercontent.com/13901751/231630017-d1671f7e-aafb-4906-909f-9601330b5e1d.svg)

Another option might be to use [GeoModelBuilder](https://github.com/rkruegs123/geo-model-builder). This is likely more difficult in practice as GMB is written in Python and would need to run as an external program.

**Comment by VladaSedlacek** [comment]
I can give this a try, probably with the Penrose component.
